# Generated by Django 5.0.4 on 2024-05-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
