# Generated by Django 5.0.4 on 2024-05-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='categories',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
